export const REFRESHKEYGENERATOR = 'REFRESH_KEY_GENERATOR_TOKEN';
export const ACCESSKEYGENERATOR = 'ACCESS_KEY_GENERATOR_TOKEN';
export const REFRESHCLAIMEXTRACTOR = 'REFRESH_CLAIM_EXTRACTOR';
export const ACCESSCLAIMEXTRACTOR = 'ACCESS_CLAIM_EXTRACTOR';
export const PUBLICACCESSTYPES = 'PUBLIC_ACCESS_TYPES';
export const NOTCLIENTTOKENTYPES = 'NOTCLIENTTOKENTYPES';